name: My First Flow
run-name: ${{github.actor}} is discovering Github Actions!!

on: [push]
jobs:
  preliminary:
    runs-on: ubuntu-latest

    steps:
      - run: echo "Starting my first job!!, running ${{ runner.os }}"
      - name: Checkout repo code
        uses: actions/checkout@v3
      - run: echo "The repo has been cloned!!!, see contents of dir"
      - name: List dir files
        run: |
          ls ${{ github.workspace }}
      - run: echo "setting up my environment!"
      - name: setup environment in node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: 16.x
      - run: echo "installing deps"
      - name: dependency installation - clean install
        run: npm ci
      - run: echo "We can test your code"
      - name: Running a test in jest
        run: |
          npm run test
      - name: "Running a failing test in jest"
        run: |
          npm run test:fail
      - name: "do not do this step if failed"
        run: echo "this step is run if there is not failure"
      - name: "do this step even if there is a failure"
        continue-on-error: true
        run: echo "this step is run **regardless**"
      - run: echo "Job(1)'s status is ${{ job.status }}"

  # on-failure:
  #   if: ${{  }}
  #   runs-on: unbuntu-latest
  #   needs: preliminary
  #   steps:
  #     - name: "on-failure step 1!!"
  #       run: |
  #         echo "on-failure step 1 is run!"
