name: My First Flow
run-name: ${{github.actor}} is discovering Github Actions!!

on: [push]
jobs:
  job1:
    runs-on: ubuntu-latest

    strategy:
      matrix:
        node-version: [16.x]

    steps:
      - run: echo "Starting my first job!!, running ${{ runner.os }}"
      - name: Checkout repo code
        uses: actions/checkout@v3
      - run: echo "The repo has been cloned!!!, see contents of dir"
      - name: List dir files
        run: |
          ls ${{ github.workspace }}
      - run: echo "setting up my environment!"
      - name: setup environment in node.js version ${{ matrix.node-version }}
        uses: actions/setup-node@v3
        with:
          node-version: ${{ matrix.node-version }}
      - run: echo "installing deps"
      - name: dependency installation - clean install
        run: npm ci
      - run: echo "We can test your code"
      - name: Running a test in jest
        run: |
          npm run test
      - name: "Running a failing test in jest"
        run: |
          npm run test:fail
      - run: echo "Job(1)'s status is ${{ job.status }}"
